[package]
name = "deck_of_cards"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
strum = { version = "0.21", features = ["derive"] }
rand = "0.8"